let javascript_scrollTriggerWideArea_general_group1=document.getElementById("javascript_scrollTriggerWideArea_general_group1");
let targetdatass={
    '0~640':[
        {
            'targetid':'generalScrollTarget1-1','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":240,"effectspeed":200,"units":"responmax|640*1200",'direction':"forward","calculate":'subtract',"limitvalue":80},{"property":"color","originvalue":[242,160,50,0.9],"effectspeed":[242,105,210,0.1],"units":"rgba","calculate":["subtract","add","add","add"],"limitvalue":[20,245,245,1]}]
        },
        {
            'targetid':'generalScrollTarget1-2','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":360,"effectspeed":320,"units":"responmax|640*1200",'direction':"forward","calculate":'subtract',"limitvalue":80},{"property":"color","originvalue":[242,160,50,0.9],"effectspeed":[242,105,210,0.1],"units":"rgba","calculate":["subtract","add","add","add"],"limitvalue":[20,245,245,1]}]
        },
        {
            'targetid':'generalScrollTarget1-1-1','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'generalScrollTarget1-2-1','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'generalScrollTarget1-2-2','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        //`,"styleoption":{"instantstyle":{"z-index":2}}},
        //{"target":`styleEffect_imgswapgroup1_zindexShow${s+1}`,"styleoption":{"animstyle":{"opacity":"0%"},"duration":400}}
        {
            'targetid':'generalScrollTarget1-3','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":180,"effectspeed":380,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-160}]
        },
        {
            'targetid':'generalScrollTarget1-3-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.3,"styleoption":{"adapt":{"animstyle":{"top":"-100%"},"duration":400,"complete":{}},"reset":{"animstyle":{"top":"0%"},"duration":400,"complete":{}}}
        }, 
        {
            'targetid':'generalScrollTarget1-4','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":300,"effectspeed":380,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-40}]
        },
        {
            'targetid':'generalScrollTarget1-4-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.6,"styleoption":{"adapt":{"animstyle":{"width":"css_responsive"},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1},"reset":{"animstyle":{"width":"0%"},"duration":400,"complete":{},"inlineresponsive_allow":"false","responsevalue_rate":1}}
        }, 
        {
            'targetid':'generalScrollTarget1-4-2','effectStyle':"scrollRateCond_instantAdapt","condValue":0.6,"styleoption":{"adapt":{"animstyle":{"width":"css_responsive"},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1},"reset":{"animstyle":{"width":"0%"},"duration":400,"complete":{},"inlineresponsive_allow":"false","responsevalue_rate":1}}
        },
        {
            'targetid':'generalScrollTargetVideo','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":76,"effectspeed":132,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'transformAnimateTarget1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[150,90,220,0.9],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmax|640*1200',"","deg"],"limitvalue":[{"rotateZ":90},{"translateZ":900},{"scale":2},{"rotateX":50}],"duration":1200}
                },
                "reset":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[0,0,0,0.8],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmax|640*1200',"","deg"],"limitvalue":[{"rotateZ":0},{"translateZ":0},{"scale":1},{"rotateX":0}],"duration":1200}
                }
            }
        },
        {
            'targetid':'transformAnimateTarget3','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1
                },
                "reset":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":0
                }
            }
        },
        {
            'targetid':'transformAnimateTarget2','effectStyle':"transformdynamic","styleoption":{"property":"transform","originvalue":[{'rotateY':0},{"rotateZ":0},{"translateX":80}],"effectspeed":[120,80,200],"units":["deg","deg","responmin|640*1200"],"calculate":["add","add","add"],"limitvalue":[{"rotateY":100},{"rotateZ":80},{"translateX":280}]}
        }
    ],
    '641~960':[
        {
            'targetid':'generalScrollTarget1-1','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":300,"effectspeed":260,"units":"responmax|960*1100",'direction':"forward","calculate":'subtract',"limitvalue":80},{"property":"color","originvalue":[242,160,50,0.9],"effectspeed":[192,85,75,0.1],"units":"rgba","calculate":["subtract","add","add","add"],"limitvalue":[50,245,125,1]}]
        },
        {
            'targetid':'generalScrollTarget1-2','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":400,"effectspeed":360,"units":"responmax|960*1100",'direction':"forward","calculate":'subtract',"limitvalue":80},{"property":"color","originvalue":[242,160,50,0.9],"effectspeed":[192,85,75,0.1],"units":"rgba","calculate":["subtract","add","add","add"],"limitvalue":[50,245,125,1]}]
        },
        {
            'targetid':'generalScrollTarget1-1-1','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'generalScrollTarget1-2-1','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'generalScrollTarget1-2-2','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        //`,"styleoption":{"instantstyle":{"z-index":2}}},
        //{"target":`styleEffect_imgswapgroup1_zindexShow${s+1}`,"styleoption":{"animstyle":{"opacity":"0%"},"duration":400}}
        {
            'targetid':'generalScrollTarget1-3','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":180,"effectspeed":380,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-160}]
        },
        {
            'targetid':'generalScrollTarget1-3-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.3,"styleoption":{"adapt":{"animstyle":{"top":"-100%"},"duration":400,"complete":{}},"reset":{"animstyle":{"top":"0%"},"duration":400,"complete":{}}}
        }, 
        {
            'targetid':'generalScrollTarget1-4','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":300,"effectspeed":380,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-40}]
        },
        {
            'targetid':'generalScrollTarget1-4-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.6,"styleoption":{"adapt":{"animstyle":{"width":"css_responsive"},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1},"reset":{"animstyle":{"width":"0%"},"duration":400,"complete":{},"inlineresponsive_allow":"false","responsevalue_rate":1}}
        },
        {
            'targetid':'generalScrollTarget1-4-2','effectStyle':"scrollRateCond_instantAdapt","condValue":0.6,"styleoption":{"adapt":{"animstyle":{"width":"css_responsive"},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1},"reset":{"animstyle":{"width":"0%"},"duration":400,"complete":{},"inlineresponsive_allow":"false","responsevalue_rate":1}}
        },
        {
            'targetid':'generalScrollTargetVideo','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":76,"effectspeed":132,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'transformAnimateTarget1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[220,90,180,0.9],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmax|960*1100',"","deg"],"limitvalue":[{"rotateZ":90},{"translateZ":900},{"scale":2},{"rotateX":50}],"duration":1200}
                },
                "reset":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[0,0,0,0.8],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmax|960*1100',"","deg"],"limitvalue":[{"rotateZ":0},{"translateZ":0},{"scale":1},{"rotateX":0}],"duration":1200}
                }
            }
        },
        {
            'targetid':'transformAnimateTarget3','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1.2
                },
                "reset":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":0
                }
            }
        },
        {
            'targetid':'transformAnimateTarget2','effectStyle':"transformdynamic","styleoption":{"property":"transform","originvalue":[{'rotateY':0},{"rotateZ":0},{"translateX":80}],"effectspeed":[140,100,200],"units":["deg","deg","responmax|960*1100"],"calculate":["add","add","add"],"limitvalue":[{"rotateY":140},{"rotateZ":100},{"translateX":280}]}
        }
    ],
    '961~9999':[
        {
            'targetid':'generalScrollTarget1-1','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":280,"effectspeed":240,"units":"responmin|1920*1080",'direction':"forward","calculate":'subtract',"limitvalue":80},{"property":"color","originvalue":[242,160,50,0.9],"effectspeed":[13,95,205,0.1],"units":"rgba","calculate":["add","add","add","add"],"limitvalue":[255,255,255,1]}]
        },
        {
            'targetid':'generalScrollTarget1-2','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":380,"effectspeed":340,"units":"responmin|1920*1080",'direction':"forward","calculate":'subtract',"limitvalue":80},{"property":"color","originvalue":[242,160,50,0.9],"effectspeed":[13,95,205,0.1],"units":"rgba","calculate":["add","add","add","add"],"limitvalue":[255,255,255,1]}]
        },
        {
            'targetid':'generalScrollTarget1-1-1','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'generalScrollTarget1-2-1','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'generalScrollTarget1-2-2','effectStyle':"dynamic","styleoption":[{"property":"opacity","originvalue":100,"effectspeed":120,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        //`,"styleoption":{"instantstyle":{"z-index":2}}},
        //{"target":`styleEffect_imgswapgroup1_zindexShow${s+1}`,"styleoption":{"animstyle":{"opacity":"0%"},"duration":400}}
        {
            'targetid':'generalScrollTarget1-3','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":180,"effectspeed":380,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-160}]
        },
        {
            'targetid':'generalScrollTarget1-3-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.3,"styleoption":{"adapt":{"animstyle":{"top":"-100%"},"duration":400,"complete":{}},"reset":{"animstyle":{"top":"0%"},"duration":400,"complete":{}}}
        }, 
        {
            'targetid':'generalScrollTarget1-4','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":300,"effectspeed":380,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-40}]
        },
        {
            'targetid':'generalScrollTarget1-4-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.6,"styleoption":{"adapt":{"animstyle":{"width":"css_responsive"},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1},"reset":{"animstyle":{"width":"0%"},"duration":400,"complete":{},"inlineresponsive_allow":"false","responsevalue_rate":1}}
        },
        {
            'targetid':'generalScrollTarget1-4-2','effectStyle':"scrollRateCond_instantAdapt","condValue":0.6,"styleoption":{"adapt":{"animstyle":{"width":"css_responsive"},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1},"reset":{"animstyle":{"width":"0%"},"duration":400,"complete":{},"inlineresponsive_allow":"false","responsevalue_rate":1}}
        },
        {
            'targetid':'generalScrollTargetVideo','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":76,"effectspeed":132,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        },
        {
            'targetid':'transformAnimateTarget1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[200,50,220,0.9],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmin|1920*1080',"","deg"],"limitvalue":[{"rotateZ":120},{"translateZ":700},{"scale":2},{"rotateX":40}],"duration":1200}
                },
                "reset":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[0,0,0,0.8],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmin|1920*1080',"","deg"],"limitvalue":[{"rotateZ":0},{"translateZ":0},{"scale":1},{"rotateX":0}],"duration":1200}
                }
            }
        },
        {
            'targetid':'transformAnimateTarget3','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1.5
                },
                "reset":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":0
                }
            }
        },
        {
            'targetid':'transformAnimateTarget2','effectStyle':"transformdynamic","styleoption":{"property":"transform","originvalue":[{'rotateY':0},{"rotateZ":0},{"translateX":80}],"effectspeed":[120,180,150],"units":["deg","deg","responmin|1920*1080"],"calculate":["add","add","add"],"limitvalue":[{"rotateY":120},{"rotateZ":180},{"translateX":200}]}
        }
    ]  
}

javascript_scrollTriggerWideArea_general_group1.setAttribute("targetdata",JSON.stringify(targetdatass));

scrollContainerGeneral_responseEffect();

let javascript_scrollTrigger_layoutVer_group1=document.getElementById("javascript_scrollTrigger_layoutVer_group1");
let targetdatass_layout={
    '0~640':[
        {
            'targetid':'javascript_scrollTrigger_layoutVerBghorizontal','effectStyle':"dynamic","styleoption":[{"property":"left","originvalue":0,"effectspeed":300,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-250}]
        },{
            'targetid':'javascript_scrollTrigger_layoutVerBgVertical','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":-200,"effectspeed":440,"units":"responmax|640*1200",'direction':"forward","calculate":'add',"limitvalue":200}]
        },{
            'targetid':'javascript_scrollTrigger_autoheightTarget1','effectStyle':"autoheight"
        },{
            'targetid':'javascript_scrollTrigger_autowidthTarget1','effectStyle':"autowidth"
        },
        {
            'targetid':'transformAnimateTarget1-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[150,90,220,0.9],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmax|640*1200',"","deg"],"limitvalue":[{"rotateZ":90},{"translateZ":900},{"scale":2},{"rotateX":50}],"duration":1200}
                },
                "reset":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[0,0,0,0.8],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmax|640*1200',"","deg"],"limitvalue":[{"rotateZ":0},{"translateZ":0},{"scale":1},{"rotateX":0}],"duration":1200}
                }
            }
        },
        {
            'targetid':'transformAnimateTarget3-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1
                },
                "reset":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":0
                }
            }
        },
        {
            'targetid':'transformAnimateTarget2-1','effectStyle':"transformdynamic","styleoption":{"property":"transform","originvalue":[{'rotateY':0},{"rotateZ":0},{"translateX":80}],"effectspeed":[120,80,200],"units":["deg","deg","responmin|640*1200"],"calculate":["add","add","add"],"limitvalue":[{"rotateY":100},{"rotateZ":80},{"translateX":280}]}
        }

        
    ],
    '641~960':[
        {
            'targetid':'javascript_scrollTrigger_layoutVerBghorizontal','effectStyle':"dynamic","styleoption":[{"property":"left","originvalue":0,"effectspeed":360,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-300}]
        }
        ,{
            'targetid':'javascript_scrollTrigger_layoutVerBgVertical','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":-300,"effectspeed":590,"units":"responmax|960*1100",'direction':"forward","calculate":'add',"limitvalue":260}]
        }
        ,{
            'targetid':'javascript_scrollTrigger_autoheightTarget1','effectStyle':"autoheight"
        },{
            'targetid':'javascript_scrollTrigger_autowidthTarget1','effectStyle':"autowidth"
        },
        {
            'targetid':'transformAnimateTarget1-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[220,90,180,0.9],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmax|960*1100',"","deg"],"limitvalue":[{"rotateZ":90},{"translateZ":900},{"scale":2},{"rotateX":50}],"duration":1200}
                },
                "reset":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[0,0,0,0.8],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmax|960*1100',"","deg"],"limitvalue":[{"rotateZ":0},{"translateZ":0},{"scale":1},{"rotateX":0}],"duration":1200}
                }
            }
        },
        {
            'targetid':'transformAnimateTarget3-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1.2
                },
                "reset":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":0
                }
            }
        },
        {
            'targetid':'transformAnimateTarget2-1','effectStyle':"transformdynamic","styleoption":{"property":"transform","originvalue":[{'rotateY':0},{"rotateZ":0},{"translateX":80}],"effectspeed":[140,100,200],"units":["deg","deg","responmax|960*1100"],"calculate":["add","add","add"],"limitvalue":[{"rotateY":140},{"rotateZ":100},{"translateX":280}]}
        }
    ],
    '961~9999':[
        {
            'targetid':'javascript_scrollTrigger_layoutVerBghorizontal','effectStyle':"dynamic","styleoption":[{"property":"left","originvalue":0,"effectspeed":450,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":-400}]
        }
        ,{
            'targetid':'javascript_scrollTrigger_layoutVerBgVertical','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":-500,"effectspeed":750,"units":"response|1920*1080",'direction':"forward","calculate":'add',"limitvalue":200}]
        }
        ,{
            'targetid':'javascript_scrollTrigger_autoheightTarget1','effectStyle':"autoheight"
        },{
            'targetid':'javascript_scrollTrigger_autowidthTarget1','effectStyle':"autowidth"
        },
        {
            'targetid':'transformAnimateTarget1-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[200,50,220,0.9],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmin|1920*1080',"","deg"],"limitvalue":[{"rotateZ":120},{"translateZ":700},{"scale":2},{"rotateX":40}],"duration":1200}
                },
                "reset":{
                    "coloranimstyle":{"property":"background-color","units":"rgba","limitvalue":[0,0,0,0.8],"duration":800},"transformanimstyle":{"property":"transform_inlinescript","units":['deg','responmin|1920*1080',"","deg"],"limitvalue":[{"rotateZ":0},{"translateZ":0},{"scale":1},{"rotateX":0}],"duration":1200}
                }
            }
        },
        {
            'targetid':'transformAnimateTarget3-1','effectStyle':"scrollRateCond_instantAdapt","condValue":0.5,"styleoption":{
                "adapt":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":1.5
                },
                "reset":{
                    "transformanimstyle":{"property":"css_responsive","duration":1200},"duration":400,"complete":{},"inlineresponsive_allow":"true","responsevalue_rate":0
                }
            }
        },
        {
            'targetid':'transformAnimateTarget2-1','effectStyle':"transformdynamic","styleoption":{"property":"transform","originvalue":[{'rotateY':0},{"rotateZ":0},{"translateX":80}],"effectspeed":[120,180,150],"units":["deg","deg","responmin|1920*1080"],"calculate":["add","add","add"],"limitvalue":[{"rotateY":120},{"rotateZ":180},{"translateX":200}]}
        }
    ]  
}
javascript_scrollTrigger_layoutVer_group1.setAttribute("targetdata",JSON.stringify(targetdatass_layout));



let javascript_scrollTrigger_layoutVer_group2=document.getElementById("javascript_scrollTrigger_layoutVer_group2");
let targetdatass_layout2={
    '0~960':[
        {
            'targetid':'scrollTriggerlayout_stepTarget1','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":800,"effectspeed":560,"units":"responmin|960*1100",'direction':"forward","calculate":'subtract',"limitvalue":240},{"property":"opacity","originvalue":0,"effectspeed":100,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget2','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1000,"effectspeed":640,"units":"responmin|960*1100",'direction':"forward","calculate":'subtract',"limitvalue":360},{"property":"opacity","originvalue":-80,"effectspeed":180,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget3','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1200,"effectspeed":720,"units":"responmin|960*1100",'direction':"forward","calculate":'subtract',"limitvalue":480},{"property":"opacity","originvalue":-160,"effectspeed":260,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget4','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1400,"effectspeed":800,"units":"responmin|960*1100",'direction':"forward","calculate":'subtract',"limitvalue":600},{"property":"opacity","originvalue":-260,"effectspeed":360,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget5','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1600,"effectspeed":880,"units":"responmin|960*1100",'direction':"forward","calculate":'subtract',"limitvalue":720},{"property":"opacity","originvalue":-320,"effectspeed":420,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget6','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1800,"effectspeed":960,"units":"responmin|960*1100",'direction':"forward","calculate":'subtract',"limitvalue":840},{"property":"opacity","originvalue":-360,"effectspeed":460,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },{
            'targetid':'atoz_processbar','effectStyle':"dynamic","styleoption":[{"property":"height","originvalue":140,"effectspeed":140,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        }
    ],
    '961~9999':[
        {
            'targetid':'scrollTriggerlayout_stepTarget1','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":800,"effectspeed":680,"units":"responmin|1920*1080",'direction':"forward","calculate":'subtract',"limitvalue":120},{"property":"opacity","originvalue":0,"effectspeed":100,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget2','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1000,"effectspeed":760,"units":"responmin|1920*1080",'direction':"forward","calculate":'subtract',"limitvalue":240},{"property":"opacity","originvalue":-80,"effectspeed":180,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget3','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1200,"effectspeed":840,"units":"responmin|1920*1080",'direction':"forward","calculate":'subtract',"limitvalue":360},{"property":"opacity","originvalue":-160,"effectspeed":260,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget4','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1400,"effectspeed":920,"units":"responmin|1920*1080",'direction':"forward","calculate":'subtract',"limitvalue":480},{"property":"opacity","originvalue":-260,"effectspeed":360,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget5','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1600,"effectspeed":1000,"units":"responmin|1920*1080",'direction':"forward","calculate":'subtract',"limitvalue":600},{"property":"opacity","originvalue":-320,"effectspeed":420,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },
        {
            'targetid':'scrollTriggerlayout_stepTarget6','effectStyle':"dynamic","styleoption":[{"property":"top","originvalue":1800,"effectspeed":1080,"units":"responmin|1920*1080",'direction':"forward","calculate":'subtract',"limitvalue":720},{"property":"opacity","originvalue":-360,"effectspeed":460,"units":"%","direction":"forward","calculate":"add","limitvalue":100}]
        },{
            'targetid':'atoz_processbar','effectStyle':"dynamic","styleoption":[{"property":"height","originvalue":140,"effectspeed":140,"units":"%",'direction':"forward","calculate":'subtract',"limitvalue":0}]
        }
    ]  
}
javascript_scrollTrigger_layoutVer_group2.setAttribute("targetdata",JSON.stringify(targetdatass_layout2));
scrollContainerLayout_responseEffect();